/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Demonstration } from "./Demonstration";
import { DemonstrationCountArgs } from "./DemonstrationCountArgs";
import { DemonstrationFindManyArgs } from "./DemonstrationFindManyArgs";
import { DemonstrationFindUniqueArgs } from "./DemonstrationFindUniqueArgs";
import { DeleteDemonstrationArgs } from "./DeleteDemonstrationArgs";
import { DemonstrationService } from "../demonstration.service";
@graphql.Resolver(() => Demonstration)
export class DemonstrationResolverBase {
  constructor(protected readonly service: DemonstrationService) {}

  async _demonstrationsMeta(
    @graphql.Args() args: DemonstrationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Demonstration])
  async demonstrations(
    @graphql.Args() args: DemonstrationFindManyArgs
  ): Promise<Demonstration[]> {
    return this.service.demonstrations(args);
  }

  @graphql.Query(() => Demonstration, { nullable: true })
  async demonstration(
    @graphql.Args() args: DemonstrationFindUniqueArgs
  ): Promise<Demonstration | null> {
    const result = await this.service.demonstration(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Demonstration)
  async deleteDemonstration(
    @graphql.Args() args: DeleteDemonstrationArgs
  ): Promise<Demonstration | null> {
    try {
      return await this.service.deleteDemonstration(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
