/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Requirement } from "./Requirement";
import { RequirementCountArgs } from "./RequirementCountArgs";
import { RequirementFindManyArgs } from "./RequirementFindManyArgs";
import { RequirementFindUniqueArgs } from "./RequirementFindUniqueArgs";
import { DeleteRequirementArgs } from "./DeleteRequirementArgs";
import { RequirementService } from "../requirement.service";
@graphql.Resolver(() => Requirement)
export class RequirementResolverBase {
  constructor(protected readonly service: RequirementService) {}

  async _requirementsMeta(
    @graphql.Args() args: RequirementCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Requirement])
  async requirements(
    @graphql.Args() args: RequirementFindManyArgs
  ): Promise<Requirement[]> {
    return this.service.requirements(args);
  }

  @graphql.Query(() => Requirement, { nullable: true })
  async requirement(
    @graphql.Args() args: RequirementFindUniqueArgs
  ): Promise<Requirement | null> {
    const result = await this.service.requirement(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Requirement)
  async deleteRequirement(
    @graphql.Args() args: DeleteRequirementArgs
  ): Promise<Requirement | null> {
    try {
      return await this.service.deleteRequirement(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
