/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ChallengeParticipation } from "./ChallengeParticipation";
import { ChallengeParticipationCountArgs } from "./ChallengeParticipationCountArgs";
import { ChallengeParticipationFindManyArgs } from "./ChallengeParticipationFindManyArgs";
import { ChallengeParticipationFindUniqueArgs } from "./ChallengeParticipationFindUniqueArgs";
import { DeleteChallengeParticipationArgs } from "./DeleteChallengeParticipationArgs";
import { ChallengeParticipationService } from "../challengeParticipation.service";
@graphql.Resolver(() => ChallengeParticipation)
export class ChallengeParticipationResolverBase {
  constructor(protected readonly service: ChallengeParticipationService) {}

  async _challengeParticipationsMeta(
    @graphql.Args() args: ChallengeParticipationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ChallengeParticipation])
  async challengeParticipations(
    @graphql.Args() args: ChallengeParticipationFindManyArgs
  ): Promise<ChallengeParticipation[]> {
    return this.service.challengeParticipations(args);
  }

  @graphql.Query(() => ChallengeParticipation, { nullable: true })
  async challengeParticipation(
    @graphql.Args() args: ChallengeParticipationFindUniqueArgs
  ): Promise<ChallengeParticipation | null> {
    const result = await this.service.challengeParticipation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ChallengeParticipation)
  async deleteChallengeParticipation(
    @graphql.Args() args: DeleteChallengeParticipationArgs
  ): Promise<ChallengeParticipation | null> {
    try {
      return await this.service.deleteChallengeParticipation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
